apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - ingress.yaml

  - frontend/deployment.yaml
  - frontend/service.yaml

  - backend/rollout.yaml
  - backend/backend-active-service.yaml
  - backend/backend-preview-service.yaml

