containers:
# ✅ Backend app
- name: backend
  image: asia-south1-docker.pkg.dev/avian-outrider-497411-v9/docker-repo/backend:v2

  ports:
  - containerPort: 3000

  env:
  - name: DB_HOST
    value: "127.0.0.1"

  - name: DB_PORT
    value: "3306"

  - name: DB_USER
    value: "dbuser"

  - name: DB_NAME
    value: "app-db"

# ✅ Cloud SQL Proxy sidecar
- name: cloudsql-proxy
  image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.7.0

  args:
  - "--structured-logs"
  - "--port=3306"
  - "avian-outrider-497411-v9:asia-south1:app-db-instance"