apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: backend
  namespace: dev
spec:
  replicas: 1

  selector:
    matchLabels:
      app: backend

  strategy:
    blueGreen:
      activeService: backend-active-service
      previewService: backend-preview-service
      autoPromotionEnabled: false   # manual promote for demo

  template:
    metadata:
      labels:
        app: backend

    spec:
      serviceAccountName: backend-sa   # ✅ RBAC integration

      containers:
      - name: backend
        image: asia-south1-docker.pkg.dev/avian-outrider-497411-v9/docker-repo/backend:v16

        ports:
        - containerPort: 3000

        env:
        - name: APP_VERSION
          value: "v16"

        # ✅ SECURITY (important)
        securityContext:
          runAsNonRoot: true
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false

        # ✅ OPTIONAL (good practice - health checks)
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10

        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 20