apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: qa

spec:
  replicas: 3   # bigger than dev

  selector:
    matchLabels:
      app: user-service

  template:
    metadata:
      labels:
        app: user-service

    spec:
      containers:
      - name: app
        image: nginx
        ports:
        - containerPort: 80
