apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-app
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/<YOUR-REPO>.git
    targetRevision: HEAD
    path: k8s/dev

  destination:
    server: https://kubernetes.default.svc
    namespace: dev

  syncPolicy:
    automated:
      prune: true
      selfHeal: true